# Generated by Django 5.0.3 on 2024-04-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='lag',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
