# Generated by Django 5.0.3 on 2024-04-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0002_link_lag'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
